### ISSUE TITLE
Broken with latest version of active admin

### ISSUE THREAD

**Issue by erdostom** [leknarf/activeadmin_async_export#2]
User AA version `1.0.0.pre1` get the following error:

````
ArgumentError in Admin::PostsController#index
wrong number of arguments (1 for 0)

Extracted source (around line #11):
         
    module Streaming

      def index
        super do |format|
          format.csv { stream_csv }
          yield(format) if block_given?

````

**Comment by MaicolBen** [comment]
Is this fixed? I checked with `1.0.0.pre1` and `1.0.0.pre2` and still the same issue

Update: Use `gem 'activeadmin_async_export', github: 'leknarf/activeadmin_async_export'` to get the last issue fixed
